version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: pytest
